hub:
   port: 4444
   remoteControlPollingIntervalInSeconds: 120
   sessionMaxIdleTimeInSeconds: 90
   newSessionMaxWaitTimeInSeconds: 5
   environments:
   
# Windows targets
      - name:     "winxp-ie6"
        browser:  "*iexplore"
      - name:	  "winxp-ie7"
        browser:  "*iexplore"
      - name:     "winxp-ie8"
        browser:  "*iexplore"
      - name:     "winxp-firefox3"
        browser:  "*firefox"
      - name:     "winxp-firefox36"
        browser:  "*firefox"
      - name:     "winxp-safari4"
        browser:  "*safari"
      - name:     "winxp-safari5"
        browser:  "*safariproxy"
      - name:     "winxp-opera10"
        browser:  "*opera"
      - name:     "winxp-googlechrome6"
        browser:  "*googlechrome"

# Linux targets
# Notice that Firefox must be named explicitly
# as "firefox-bin" to be able to close the browser.
# The exact installation directory of Firefox varies.
# Typical locations are:
#  /opt/firefox/firefox-bin
#  /usr/lib/firefox/firefox-bin
#  /usr/local/firefox/firefox-bin
#  /usr/local/lib/firefox/firefox-bin
      - name:     "linux-firefox3"
        browser:  "*firefox /usr/lib/firefox/firefox-bin"
      - name:     "linux-firefox36"
        browser:  "*firefox /usr/lib/firefox/firefox-bin"
      - name:     "linux-opera10"
        browser:  "*opera"
      - name:     "linux-googlechrome6"
        browser:  "*googlechrome"

# Mac OS X targets
      - name:     "osx-firefox35"
        browser:  "*firefox"
      - name:     "osx-safari4"
        browser:  "*safari"
      - name:     "osx-opera10"
        browser:  "*opera"
#      - name:     "osx-googlechrome6"
#        browser:  "*googlechrome /Application/Google Chrome.app/Contents/MacOS/Google Chrome"
